CREATE SCHEMA IF NOT EXISTS identity;
CREATE SCHEMA IF NOT EXISTS reporting;
CREATE SCHEMA IF NOT EXISTS media;
CREATE SCHEMA IF NOT EXISTS inspector;
CREATE SCHEMA IF NOT EXISTS management;

-- MANAGEMENT.INSTITUTIONS
CREATE TABLE IF NOT EXISTS management.institutions (
  id          bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        varchar(255) NOT NULL,
  slug        varchar(255) NOT NULL UNIQUE,
  is_active   boolean      NOT NULL DEFAULT true,
  created_at  timestamptz  NOT NULL DEFAULT NOW(),
  updated_at  timestamptz  NOT NULL DEFAULT NOW()
);

-- IDENTITY.USERS
CREATE TABLE IF NOT EXISTS identity.users (
  id                    bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  citizen_id            varchar(13)  NOT NULL,
  email                 varchar(255) NOT NULL,
  username              varchar(100) NOT NULL,
  password_hash         varchar(255) NOT NULL,
  is_active             boolean      NOT NULL,
  is_email_verified     boolean      NOT NULL,
  failed_login_attempts integer      NOT NULL,
  profile_image_path    varchar(500) NULL,
  last_login_at         timestamptz  NULL,
  created_at            timestamptz  NOT NULL,
  updated_at            timestamptz  NOT NULL,
  deleted_at            timestamptz  NULL,
  user_type             varchar(50)  NOT NULL,
  institution_id        bigint       NULL REFERENCES management.institutions(id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS users_citizen_id_uq
  ON identity.users (citizen_id);

CREATE UNIQUE INDEX IF NOT EXISTS users_email_uq
  ON identity.users (email);

CREATE UNIQUE INDEX IF NOT EXISTS users_username_uq
  ON identity.users (username);

-- REPORTING.REPORTS
CREATE TABLE IF NOT EXISTS reporting.reports (
  id                    bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_by            bigint       NOT NULL,
  assigned_inspector_id bigint       NULL,
  category              varchar(100) NOT NULL,
  status                varchar(50)  NOT NULL,
  title                 varchar(200) NOT NULL,
  description           text         NOT NULL,
  created_at            timestamptz  NOT NULL,
  updated_at            timestamptz  NOT NULL,

  CONSTRAINT reports_created_by_fk
    FOREIGN KEY (created_by)
    REFERENCES identity.users (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT reports_assigned_inspector_fk
    FOREIGN KEY (assigned_inspector_id)
    REFERENCES identity.users (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS reports_created_by_idx
  ON reporting.reports (created_by);

CREATE INDEX IF NOT EXISTS reports_assigned_inspector_idx
  ON reporting.reports (assigned_inspector_id);

-- REPORTING.REPORT_LOCATIONS (1 location per report)
CREATE TABLE IF NOT EXISTS reporting.report_locations (
  report_id   bigint        PRIMARY KEY,
  latitude    numeric(10,7) NOT NULL,
  longitude   numeric(10,7) NOT NULL,
  address     varchar(500)  NOT NULL,

  CONSTRAINT report_locations_report_fk
    FOREIGN KEY (report_id)
    REFERENCES reporting.reports (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE
);

-- MEDIA.FILES
CREATE TABLE IF NOT EXISTS media.files (
  id               bigserial    PRIMARY KEY,
  file_type        varchar(10)  NOT NULL,
  original_name    varchar(255) NOT NULL,
  stored_name      varchar(255) NOT NULL,
  mime_type        varchar(100) NOT NULL,
  size_bytes       bigint       NOT NULL,
  storage_provider varchar(50)  NOT NULL,
  storage_path     varchar(500) NOT NULL,
  report_id        bigint       NOT NULL,
  uploaded_by      bigint       NOT NULL,
  uploaded_at      timestamptz  NOT NULL,

  CONSTRAINT files_report_fk
    FOREIGN KEY (report_id)
    REFERENCES reporting.reports (id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT files_uploaded_by_fk
    FOREIGN KEY (uploaded_by)
    REFERENCES identity.users (id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS files_report_id_idx
  ON media.files (report_id);

CREATE INDEX IF NOT EXISTS files_uploaded_by_idx
  ON media.files (uploaded_by);

-- INSPECTOR.INSPECTIONS
CREATE TABLE IF NOT EXISTS inspector.inspections (
  id              bigint       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id       bigint       NOT NULL,
  inspector_id    bigint       NOT NULL,
  status          varchar(50)  NOT NULL DEFAULT 'PENDING',
  notes           text         NULL,
  assigned_at     timestamptz  NOT NULL DEFAULT NOW(),
  updated_at      timestamptz  NOT NULL DEFAULT NOW(),
  resolved_at     timestamptz  NULL,

  CONSTRAINT inspections_report_fk
    FOREIGN KEY (report_id)
    REFERENCES reporting.reports (id)
    ON UPDATE CASCADE ON DELETE RESTRICT,

  CONSTRAINT inspections_inspector_fk
    FOREIGN KEY (inspector_id)
    REFERENCES identity.users (id)
    ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS inspections_inspector_id_idx
  ON inspector.inspections (inspector_id);

CREATE INDEX IF NOT EXISTS inspections_report_id_idx
  ON inspector.inspections (report_id);

CREATE INDEX IF NOT EXISTS inspections_status_idx
  ON inspector.inspections (status);